### ISSUE TITLE
Q: About implementation table

### ISSUE THREAD

**Issue by mikevoronov** [bytecodealliance/wasm-interface-types#58]
Hi, I am trying to figure out with a binary encoding of Wasm interface types, especially with [implementation](https://github.com/bytecodealliance/wasm-interface-types/blob/main/BINARY.md#implement-subsection-4) subsection. As far as I know, there is no binary encoding standart for Wasm IT at now (and no implementation subsection according to [here](https://github.com/WebAssembly/interface-types/issues/119#issuecomment-649696588)), but both Wasmtime and Wasmer use this table to link adapter with core function. Is there really no this table in the standard and this subsection is self-defined?

And maybe it is really better (according to answers from this [issue](https://github.com/WebAssembly/interface-types/issues/119)) to link adapter with core funcs by it's name with checking type matching?

**Comment by alexcrichton** [comment]
The current upstream proposal is a little hand-wavy in terms of binary representation, but that's just because it's a very early-days representation of the proposal. I think there's still major changes in the works so it doesn't make too much sense to hammer something down right now. This repo was intended to have a work-in-progress style implementation of the encoding/decoding. 

This repo is even likely to go away soon as the interface types spec progresses since it's likely that these definitions and such will go in the core tooling.

**Comment by mikevoronov** [comment]
Got it, thank you for the answer.
